//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTiendaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmpleadoTienda
    {
        public string Nombres { get; set; }
        public string Cargo { get; set; }
        public string NombreTienda { get; set; }
        public string Mes { get; set; }
        public string Dia { get; set; }
    }
}
